<div class="inner MetFlash">
  <div id="scroll1" style="height: 250px">
    <ul style="margin: 0; list-style: none; padding: 0;">
      <li>
        <img src="http://tmp.metinfo.cn/met094/upload/201306/1372142428.jpg" style="width: 960px;
                        height: 250px" />
      </li>
      <li>
        <img src="http://tmp.metinfo.cn/met094/upload/201306/1372142868.jpg" style="width: 960px;
                        height: 250px" />
      </li>
    </ul>
  </div>
</div>
<script type="text/javascript">
  var scroll1 = new scroller('scroll1', { direction: 'left', unit: 900 }, 3000);
</script>