
<div class="container" style="background:url(${page.tpath}/themes/banner/banner.gif) no-repeat;margin:0 auto;padding:70px 0 50px 0;background-size:100%">
 
    <div class="category_title" style="padding-left:70px">
        <strong>${category.name}</strong><br />
        <em id="category_title_em">${category.tag}</em>
    </div>
    <script>
        var cem=document.getElementById('category_title_em');
    	cem.innerHTML=cem.innerHTML.toUpperCase();
    </script>
</div>