

<div id="bottombj">
<div id="bottom">
                   
<div class="link">友情链接：
$link('2','<a href="{url}" target="_blank">{text}</a>')
    </div>                                
   </div>
   </div>
   
     <div class="mainnav">
  <div class="cen">
    <ul class="ulnav"><h5>关于鑫汇达</h5>
      <li><a href="/page/guanyuwomen.html">公司简介</a></li>
      <li><a href="/page/qiyewenhua.html">企业文化</a></li>
      <li><a href="/page/fuwuchengnuo.html">服务承诺</a></li>
      <li><a href="/page/rongyuzizhi.html">资质荣誉</a></li>
      <li><a href="/page/lianxiwomen.html">联系我们</a></li>
    </ul>
    <ul class="ulnav"><h5>产品解决方案</h5>
      <li><a href="/chanpinliebiao">产品中心</a></li>
      <li><a href="/chenggonganli">工程案例</a></li>
      <li><a href="/xinwenzixun">新闻中心</a></li>
      
    </ul>
     <div class="contacti">
        <h3>青岛鑫汇达消毒净化设备有限公司</h3><p>

联系电话：0532-82292723<br>
传　真：0532-82293923<br>
网　址：www.qdxhdjh.com<br>
地　址：青岛胶州市高州北路88号
</p>

<p></p>
     </div>
     
    <div class="clear"></div>
  </div>

</div>

<div class="bot">

  <div class="cop"><p><span id="ctl00_foot2_Label2"><span style="color: #ffffff">Copyright &copy; 2014-2015,www.qdxhdjh.com,All rights reserved 优化推广：QQ：2681508425<br />
版权所有 &copy;<span style="white-space: normal; word-spacing: 0px; text-transform: none; float: none; font: 12px Simsun; display: inline !important; letter-spacing: normal; text-indent: 0px; -webkit-text-stroke-width: 0px">青岛鑫汇达消毒净化设备有限公司</span> 未经许可 严禁复制 建议使用1024X768分辨率浏览本站<br />
&nbsp;&nbsp;</span><a href="/admin"><span style="color: #ffffff">管理员后台</span></a><span style="color: #ffffff"> </span><script type="text/javascript">var cnzz_protocol = (("https:" == document.location.protocol) ? " https://" : " http://");document.write(unescape("%3Cspan id='cnzz_stat_icon_1254188508'%3E%3C/span%3E%3Cscript src='" + cnzz_protocol + "s95.cnzz.com/z_stat.php%3Fid%3D1254188508%26show%3Dpic1' type='text/javascript'%3E%3C/script%3E"));</script>
<script type="text/javascript">
var _bdhmProtocol = (("https:" == document.location.protocol) ? " https://" : " http://");
document.write(unescape("%3Cscript src='" + _bdhmProtocol + "hm.baidu.com/h.js%3F1cc312c87734e17398a77ad7ae59fe98' type='text/javascript'%3E%3C/script%3E"));
</script></span></p></div>
</div>


     
   <div > 


<DIV id=STATICMENU 
            
    style="Z-INDEX: 999; RIGHT: 10px; VISIBILITY: visible; WIDTH: 103px; POSITION: absolute; TOP: 259px;  background-image:url('${page.tpath}/images/qq_02.gif')">
  <table width="100%" cellspacing="0" cellpadding="0">
    <tr>
      <td><img src="${page.tpath}/images/qq_01.gif" width="103" height="36"></td>
    </tr>
    <tr>
      <td style="background-image:url('images/qq_02.gif')">
     
        <tr><td>&nbsp; <a href="tencent://message/?uin=3133930365&amp;Menu=yes" target=blank><img src="http://wpa.qq.com/pa?p=4:3133930365:4" align=absMiddle border=0>&nbsp; 在线客服</a></td></tr>
      
      </td>
    </tr>
    <tr>
      <td height="44" width="103" valign="bottom" background="${page.tpath}/images/qq_03.gif"><table width="100%" cellspacing="0" cellpadding="0">
        <tr>
          <td height="5"><img src="${page.tpath}/images/qq_03.gif" width="103" height="44"></td>
        </tr>
      </table></td>
    </tr>
  </table>
  <SCRIPT language=javascript>

var stmnGAP1 = 70; 
var stmnGAP2 = 325; 
var stmnBASE = 70; 
var stmnActivateSpeed = 200;
var stmnScrollSpeed = 10;

var stmnTimer;

function RefreshStaticMenu()
{
var stmnStartPoint, stmnEndPoint, stmnRefreshTimer;

stmnStartPoint = parseInt(STATICMENU.style.top, 10);
stmnEndPoint = document.body.scrollTop + stmnGAP2;
if (stmnEndPoint < stmnGAP1) stmnEndPoint = stmnGAP1;

stmnRefreshTimer = stmnActivateSpeed;

if ( stmnStartPoint != stmnEndPoint ) {
                stmnScrollAmount = Math.ceil( Math.abs( stmnEndPoint - stmnStartPoint ) / 15 );
                STATICMENU.style.top = parseInt(STATICMENU.style.top, 10) + ( ( stmnEndPoint<stmnStartPoint ) ? -stmnScrollAmount : stmnScrollAmount );
                stmnRefreshTimer = stmnScrollSpeed;
}

stmnTimer = setTimeout ("RefreshStaticMenu();", stmnRefreshTimer);
}

                STATICMENU.style.top = document.body.scrollTop + stmnBASE;
                RefreshStaticMenu();

      </SCRIPT>
</DIV></div>



<script type="text/javascript" language="javascript" src="${page.tpath}/js/picAutoZoom.js" ></script>
<script type="text/javascript" language="javascript">
<!--
    $.ajaxSetup({
        timeout: 300000
    });
//-->
</script>

<script type="text/javascript">
//<![CDATA[
var theForm = document.forms['aspnetForm'];
if (!theForm) {
    theForm = document.aspnetForm;
}
function __doPostBack(eventTarget, eventArgument) {
    if (!theForm.onsubmit || (theForm.onsubmit() != false)) {
        theForm.__EVENTTARGET.value = eventTarget;
        theForm.__EVENTARGUMENT.value = eventArgument;
        theForm.submit();
    }
}
//]]>
</script>

    <script language="JavaScript" src="http://code.54kefu.net/kefu/js/159/781959.js" type="text/javascript" charset="utf-8"></script>
    <a class="bshareDiv" href="http://www.bshare.cn/share">分享按钮</a><script type="text/javascript" charset="utf-8" src="http://static.bshare.cn/b/buttonLite.js#uuid=3a5496e1-2b4f-4b06-ba86-d871b1f0e4e2&style=3&fs=3&textcolor=#ffffff&bgcolor=#99cc33&bp=qqmb,bsharesync,sinaminiblog,qzone,189share,sohuminiblog,renren,xinhuamb,tianya,shouji,ifengmb,neteasemb,qqxiaoyou,kaixin001,weixin,douban,qqim&text=分享到"></script>
