<div id="head">
     <div class="logo">
          <div class="logol"><img src="${page.tpath}/images/logo.jpg"></div>
          <div class="logor">
         <div class="logort"><img src="${page.tpath}/images/shouye.jpg" border="0" usemap="#Map">
           <map name="Map" id="Map">
             <area shape="rect" coords="46,7,111,28" onclick="this.style.behavior='url(#default#homepage)';this.setHomePage('./');" 
            href="default.htm" />
             <area shape="rect" coords="108,3,167,27" href="javascript:window.external.addFavorite('./','青岛鑫汇达消毒净化设备有限公司');" />
             <area shape="rect" coords="167,3,232,27" href="single.aspx@cid=2&n1=1" />
           </map>
         </div>
         <div class="logorb"><img src="${page.tpath}/images/phone.gif"></div>
     </div>
     </div>
     <div class="nav">
          <div  id="menumain">
      <div id="mainmenuiner">
                    <a href="/" class="menumain">网站首页</a>
    
                    <a href="/page/guanyuwomen.html" class="menumain">关于我们</a>
    
                    <a href="/chanpinliebiao" class="menumain">产品中心</a>
    
                    <a href="/xinwenzixun" class="menumain">新闻中心</a>
    
                    <a href="/page/qiyewenhua.html" class="menumain">企业文化</a>
    
                    <a href="/page/fuwuchengnuo.html" class="menumain">服务承诺</a>
    
                    <a href="/chenggonganli" class="menumain">成功案例</a>
    
                    <a href="/page/rongyuzizhi.html" class="menumain">荣誉资质</a>
    
                    <a href="/page/lianxiwomen.html" class="menumain">联系我们</a>
    </div>
    </div>
     </div>

     <div class="banner">
          <object classid="clsid:D27CDB6E-AE6D-11cf-96B8-444553540000" id=scriptmain name=scriptmain 
codebase="http://download.macromedia.com/pub/shockwave/cabs/
flash/swflash.cab#version=6,0,29,0" width="1002" height="329">
    <param name="movie" value="${page.tpath}/images/lbxml.swf?bcastr_xml_url=${page.tpath}/images/lbxml.xml?g=0||1">
    <param name="quality" value="high">
    <param name=scale value=noscale>
    <param name="LOOP" value="false">
    <param name="menu" value="false">
    <param name="wmode" value="transparent">
    <embed src="${page.tpath}/images/lbxml.swf?bcastr_xml_url=${page.tpath}/images/lbxml.xml?g=0|" width="1002" height="329"  
    loop="false" quality="high" pluginspage="http://www.macromedia.com/go/getflashplayer" 
    type="application/x-shockwave-flash" salign="T" name="scriptmain" menu="false" wmode="transparent">
    </embed>
  </object>
     </div>
</div>