<header class="page-header">
    <div class="container">
        <div class="logo">
            <img src="${page.tpath}/themes/logo.png" width="80%"/>
            <a href="/"></a>
        </div>
        
        <div class="contact">
           <!--<span class="lft">
               <img src="${page.tpath}/themes/cms-qr.png" width="60" height="60"/>
               <br />微信公众号
            </span>-->
            
            热线电话：<br />$site(tel)<br />
            0757—82013999(15线)
        </div>
       
    </div>

    <div class="clear-fix"></div>
</header>


<div id="navigator" class="page-navigator">
    <div class="left"></div><div class="right"></div>
    <div class="navs">
        <ul>
        <li class="first "><a href="${page.domain}" title="网站首页">网站首页</a></li>
            <li class="parent "><a href="${page.domain}/about/intro.html" title="了解天兴">了解天兴</a></li>
          
            <li class="parent "><a href="//txxf.c.k3f.net/cn/product/" title="产品展示">产品展示</a></li>
            <!--<li class="last "><a href="//txxf.c.k3f.net/cn/proxy-brand/" title="品牌代理">品牌代理</a></li>-->
        <li><a href="${page.domain}/case/" title="工程案例">工程案例</a></li>
        <li><a href="${page.domain}/article/" title="新闻资讯">新闻资讯</a></li>
       
        </ul>
        <div class="clear"></div>
    </div>
</div>

<div class="page-sub-navigator">
    <div class="clear"></div>
    <ul class="menu"><li class="first "><a href="//txxf.c.k3f.net/cn/about/intro.html" title="公司介绍">公司介绍</a></li>
        <li><a href="//txxf.c.k3f.net/cn/about/develop.html" title="公司历程">公司历程</a></li>
        <li><a href="//txxf.c.k3f.net/cn/about/culture.html" title="企业文化">企业文化</a></li>
        <li class="last "><a href="//txxf.c.k3f.net/cn/about/qualification.html" title="资质荣誉">资质荣誉</a></li>
    </ul>
    <div class="clear"></div>
    <div class="hr2"></div>
</div>


<div class="clear-fix"></div>





