//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JR.Stand.Toolkit.Crawl.Impl {
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class WebManageResource {
        
        private static System.Resources.ResourceManager resourceMan;
        
        private static System.Globalization.CultureInfo resourceCulture;
        
        [System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal WebManageResource() {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Resources.ResourceManager ResourceManager {
            get {
                if (object.Equals(null, resourceMan)) {
                    System.Resources.ResourceManager temp = new System.Resources.ResourceManager("JR.Stand.Toolkit.Crawl.Impl.WebManageResource", typeof(WebManageResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        public static System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        public static string create_project {
            get {
                return ResourceManager.GetString("create_project", resourceCulture);
            }
        }
        
        public static string delete_project {
            get {
                return ResourceManager.GetString("delete_project", resourceCulture);
            }
        }
        
        public static string error {
            get {
                return ResourceManager.GetString("error", resourceCulture);
            }
        }
        
        public static string invoke_collect {
            get {
                return ResourceManager.GetString("invoke_collect", resourceCulture);
            }
        }
        
        public static string partial_navigator {
            get {
                return ResourceManager.GetString("partial_navigator", resourceCulture);
            }
        }
        
        public static string project_list {
            get {
                return ResourceManager.GetString("project_list", resourceCulture);
            }
        }
        
        public static string test_result {
            get {
                return ResourceManager.GetString("test_result", resourceCulture);
            }
        }
        
        public static string update_project {
            get {
                return ResourceManager.GetString("update_project", resourceCulture);
            }
        }
        
        public static string style {
            get {
                return ResourceManager.GetString("style", resourceCulture);
            }
        }
        
        public static string welcome_page {
            get {
                return ResourceManager.GetString("welcome_page", resourceCulture);
            }
        }
    }
}
