<div class="product-nav clearfix">
  	<div class="title pull-left">
        <a href="/product/demo/set-up-demo.html">美助理管理软件设置<i class="fa fa-caret-down"></i></a></div>
  	<ul class="pro-nav-info pull-left mod-prod-menu">
      	<li menu-data="首页"><a class="active" href="/product/">首页</a></li>
      	<li menu-data="收银"><a href="/product/demo/cashier-demo.html">收银</a></li>
      	<li menu-data="订单"><a href="/product/demo/order-demo.html">订单</a></li>
      	<li menu-data="会员"><a href="/product/demo/customer-demo.html">会员</a></li>
      	<li menu-data="营销"><a href="/product/demo/marketing-demo.html">营销</a></li>
      	<li menu-data="财务"><a href="/product/demo/finance-demo.html">财务</a></li>
        <li menu-data="库存"><a href="/product/demo/warehouse-demo.html">库存</a></li>

  	</ul>
    <div class="nav-right-btn"><a href="#"><img src="${page.tpath}/images/pro-icon01.jpg"></a>
      <a href="#"><img src="${page.tpath}/images/pro-icon02.jpg"></a>
      <a href="#"><img src="${page.tpath}/images/pro-icon03.jpg"></a>
    </div>
</div>
