<!--foot-->
<div class="foot">
  <div class="foot-top">
    <div class="container">
      <div class="row">
        <ul class="foot-nav text-center">
            <li><a href="/"><img src="${page.tpath}/images/logo.png"></a></li>
            $links(1,10,'<li><a href="{url}">{text}</a></li>')
         
        </ul>
      </div>
    </div>
  </div>
  <div class="copyright">
    <div class="container">
      <div class="row">©版权所有Copyright(C)2018 上海圆球网络科技有限公司
          <span class="line">|</span>ICP备案号：<!--沪ICP备15027453号-1-->沪ICP备18023823号-1
          <span class="line">|</span>联系电话：$site(tel)</div>
    </div>
  </div>
</div>
<div style="display:none;">

<!--百度统计代码-->
    
<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?547282da427f358428eab71b79905c06";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?94603d45da894e5940d309769283219d";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script>
    
    
<!--cnzz-->
    
<script src="https://s22.cnzz.com/z_stat.php?id=1262362824&web_id=1262362824" language="JavaScript"></script>
</div>
    
<!--百度客服-->

<script>
var _hmt = _hmt || [];
(function() {
  var hm = document.createElement("script");
  hm.src = "https://hm.baidu.com/hm.js?a94d542e536ffbd65b938b0a633112bd";
  var s = document.getElementsByTagName("script")[0]; 
  s.parentNode.insertBefore(hm, s);
})();
</script> 
<!--360-->

<script>(function(){
var src = (document.location.protocol == "http:") ? "http://js.passport.qihucdn.com/11.0.1.js?5e88d7029ee51d5375984997314a80dc":"https://jspassport.ssl.qhimg.com/11.0.1.js?5e88d7029ee51d5375984997314a80dc";
document.write('<script src="' + src + '" id="sozz"><\/script>');
})();
</script>