<div class="header hidden-xs">
  <ul class="clearfix text-center">
      <li><a href="/"><img src="${page.tpath}/images/logo.png"></a></li>
      $links(1,10,'<li><a href="{url}">{text}</a></li>')
  </ul>
</div>
<div class="mobile-header visible-xs">
    <div class="logo text-center clearfix">
        <a class="nav-bars1 pull-left mod-mo-nav-bar" data-toggle1="offcanvas" data-target1=".navmenu" href="javascript:void(0)" > 
            <i class="fa fa-bars"></i> </a>
        <a href="/"><img src="${page.tpath}/images/logo.png"></a><a class="pull-right" href="/partner/">伙伴</a>
    </div>
    
    <div class="mobile-hd-nav">
    <div id="kuaizhan-navbar-default" class="navmenu navmenu-default nav-side-menu navmenu-fixed-left1 offcanvas-md1">
      <div id="header-mbmenu" class="menu-list">
      <ul id="menu-content" class="menu-content out in">
          $links(1,10,'<li><a href="{url}" target="{target}">{text}</a></li>')
      </ul>
    </div>
        </div>
  </div>
</div>