<!-- 页脚文件 -->
<div id="footer">
    <div class="footer-main">
        <div class="footer-logo"></div>
        <div class="footer-links">
            <a href="#">回到顶部</a> $link(3,'|<a href="{url}"{target}>{text}</a>',-1)
        </div>
        <div class="footer-main-contact">
            <ul>
                <li>${site.tel}1</li>
                <li>${site.address}</li>
                <li>${site.email}</li>
        	</ul>
        </div>
        
        版权所有 Copyright(C)2010-2014 ${site.name}&nbsp;&nbsp;&nbsp;&nbsp;沪ICP备128872308号&nbsp;&nbsp;&nbsp;&nbsp;
        网络支持：<a href="http://www.ops.cc" target="_blank" style="color:#fff;text-decoration:none;">奥博网络</a>
    </div>
</div>
    

