<div id="footer">
<div id="footblock">
</div><div class="right">
<p class="title" style="border:none;"><span>LMS</span></p>
    <a href="${page.domain}/service/aboutus.html">$lang(aboutus)</a> |<a href="${page.domain}/product.html">$lang(machines)</a> |
    <a href="${page.domain}/service/feedback.html">$lang(feedback)</a> | <a href="${page.domain}/service/sitemap.html">$lang(sitemap)</a> | 
    <a href="${page.domain}/service/contactus.html">$lang(contactus)</a><!--blog--><!--|<a href="http://www.lmsmachinery.com/zblog/">blog</a>-->
<br />

    <a href="http://www.lmsmachinery.com">LMS International Limted </a> <br />
<strong>Add:</strong>$site(address)<strong>Post Code:</strong>$site(postcode)<br />
<strong>Tel:</strong>$site(tel)<strong> &nbsp;Fax:</strong>$site(fax)<br />
<strong>E-mail:</strong> <a href="mailto:$site(email)" onclick="ga('send','event','link','click','$site(email)');" >$site(email)</a>&nbsp;
<a href="mailto:zhuyongdong@gmail.com" onclick="ga('send','event','link','click','zhuyongdong@gmail.com');" >zhuyongdong@gmail.com</a>&nbsp;
    <img alt="" src="/images/18140449218.jpg" />:<a href="callto://allyrafter">allyrafter</a>&nbsp;
    
     <a href="https://www.facebook.com/machinerylms" target="_blank">
        <img src="/resources/s1/image/201405/20140515094138_1436.jpg" style="border:0;width:20px"/>
         Facbook</a>&nbsp;
    <a href="https://www.youtube.com/user/machinerylms" target="_blank">
        <img src="/resources/s1/image/201405/20140515094942_5897.gif" style="border:0;width:20px"/>
        YouTube</a><!--
    &nbsp;
    <a href="http://lnzmachinery.en.alibaba.com/" target="_blank">
        <img src="/resources/s2/image/201405/20140520043132_3662.gif" style="border:0;width:20px"/>
        Alibaba</a>-->
    <br />
Contact:
    <a href="mailto:service@lmsmachinery.com" onclick="ga('send','event','link','click','service@lmsmachinery.com');">service@lmsmachinery.com</a>
    &nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
<a href="http://www.miibeian.gov.cn" rel="nofollow"  target="_blank">蜀ICP备09005773号</a> 
    <span style="color:black" title="Technology Support"><a href="http://www.ops.cc/cms/" rel="nofollow" style="text-decoration:none">OPSoft</a></span>
 </div>
    