
<!--nav start-->
<div class="system-nav">
  <div class="container">
    <div class="row">
      <div class="col-sm-10 col-xs-12">
        <ul class="industry-nav text-center">                                                                                                      
        	<li>适用行业：</li>
            <li><a href="#">美容院</a></li>
            <li><a href="#">理发店</a></li>
            <li><a href="#">足浴按摩店</a></li>
            <li><a href="#">健身房</a></li>
            <li><a href="#">宠物店</a></li>
            <li><a href="#">汽车服务</a></li>
        </ul>
      </div>
      <div class="col-sm-2 col-xs-12">
        <div class="system-nav-right text-right" id="buy"><a class="sub-btn" data-toggle="collapse" data-parent="#buy" href="#collapsebuy">购买</a></div>
    </div>
  </div>
</div>
</div>
<div id="collapsebuy" class="panel-collapse collapse sub-collapse">
  <div class="container">
    <div class="row buy-info">
    <div class="table-responsive">
      <table width="100%" border="0" cellspacing="0" cellpadding="0" class="table buy-table">
  <tbody>
      <!--
    <tr>
      <td>&nbsp;</td>
      <td class="blue-txt text-right">（7人以下店铺）</td>
      <td class="blue-txt text-right">（7人以上店铺）</td>
    </tr>-->
    <tr>
      <td><b>基础版：</b>收银+会员管理+短信营销+会员营销+财务报表+微信会员卡+微信员工端+库存+员工分红</td>
      <td class="text-right"><label class="input-label"><input class="input-radio" type="checkbox" name="">
        <span class="input-checkbox input-radioInput"></span>
    </label><span class="price">1999</span></td>
     
    </tr>
    <tr>
      <td><b>初级营销版：</b>一元团购+基础版</td>
      <td class="text-right"><label class="input-label"><input class="input-radio" type="checkbox" name="">
        <span class="input-checkbox input-radioInput"></span>
    </label><span class="price">4999</span></td>
     
    </tr>
    <tr>
      <td><b>高级营销版：</b>联盟分红+初级营销版</td>
        <td class="text-right"><label class="input-label"><input class="input-radio" type="checkbox" name="">
        <span class="input-checkbox input-radioInput"></span>
          </label><span class="price">19999</span></td>
    
    </tr>
   <!--
    <tr>
      <td colspan="3" class="text-right total-txt">合计： 1866元</td>
    </tr>-->
  </tbody>
</table>
<div class="clearfix buy-bottom-txt">
	<div class="col-sm-6 col-xs-12 bottom-txt-left"><!--注：小型店铺7人以下使用、中大型店铺7人以上使用--></div>
    <div class="col-sm-6 col-xs-12 bottom-txt-right text-right">请下载软件试用，在软件内付费</div>
</div>
</div>
      
    </div>
  </div>
</div>

<div class="sub-section section-04 section-product text-center">
	<div class="container">
    <div class="row">
    	<div class="col-sm-7 col-xs-12 section-04-txt">
            <h1 class="fadeIn wow headline" data-wow-duration="2s" data-wow-delay="0">美助理微信电子会员卡</h1>
            <h2 class="fadeIn wow subheadline" data-wow-duration="2s" data-wow-delay="0.5s">给老板省钱<span class="mar-20">让顾客放心</span></h2>
            <div class="fadeIn wow sub-more"  data-wow-duration="2s"  data-wow-delay="1s"><a href="mzl-wechat-card.html">进一步了解 ></a></div></div>
    	
    	<div class="col-sm-5 col-xs-12"><img class="fadeInRight wow pull-left" data-wow-duration="2s" src="${page.tpath}/images/phone-img02.jpg"></div>
    </div>
    </div>
</div>
<div class="sub-section grey-bg section-product section-product-bottom text-center">
	<div class="container">
    <div class="row">
    	<h1 class="fadeIn wow headline" data-wow-duration="2s" data-wow-delay="0s">美助理微信员工端</h1>
    	<h2 class="fadeIn wow subheadline" data-wow-duration="2s" data-wow-delay="0.3s">化繁为简<span class="mar-40">让每个员工都成为营销高手融洽</span></h2>
        <div class="fadeIn wow sub-more"  data-wow-duration="2s"  data-wow-delay="0.5s"><a href="mzl-wechat-employee.html">进一步了解 ></a></div>
        <div class="fadeIn wow"  data-wow-duration="2s"  data-wow-delay="0.8s">
        	<ul class="clearfix market-info">
            	<li class="col-sm-2 col-xs-4"><span class="market-item">开卡营销</span></li>
                <li class="col-sm-2 col-xs-4"><span class="market-item">充值营销</span></li>
                <li class="col-sm-2 col-xs-4"><span class="market-item">发券营销</span></li>
                <li class="col-sm-2 col-xs-4"><span class="market-item">抽奖营销</span></li>
                <li class="col-sm-2 col-xs-4"><span class="market-item">客勤维护</span></li>
                <li class="col-sm-2 col-xs-4"><span class="market-item">业绩提成</span></li>
            </ul>
        </div>
        <div class="fadeIn wow"  data-wow-duration="2s"  data-wow-delay="1s"><img src="${page.tpath}/images/phone-img03.jpg"></div>
    </div>
    </div>
</div>