<style type="text/css">
    .bannerBG{background:#e3e3e3;}
#fla{margin:0 auto;}
#fla ul{list-style:none;margin:0;padding:0;}
#fla ul li{float:left;}
#fla_pager{position:absolute;bottom:-5px;}
    .flashDiv .pager{position:absolute;bottom:0;left:35px;margin:0;overflow:hidden;}
    .flashDiv .pager a{opacity:0.8;filter:alpha(opacity=80);display:inline-block;border:solid 0px #666;/*padding:4px 8px;*/
        background:#ddd;text-decoration:none;color:#fff;font-weight:bold;
        height:5px; width:110px;text-indent:-999em;line-height:15px;padding-right:3px;color:#006699;
    	}
    .flashDiv .pager a.current{background:#006fab;color:#666;}
    .flashDiv img{width:950px;height:250px;}
</style>
<div class="bannerBG">
<div style="width:950px;margin:0 auto;">
<div class="center flashDiv" id="fla" style="height:250px;overflow:hidden">
  <ul>
      <li><img src="${page.resdomain}/resources/s1/image/201403/20140323083904_4685.jpg" alt="成功道路"/></li>
      <li><img src="${page.resdomain}/resources/s1/image/201403/20140323085137_8569.jpg" alt="成人高考考前辅导"/></li>
      <li><img src="${page.resdomain}/resources/s1/image/201403/20140323085837_0366.jpg" alt="教师资格证"/></li>
      <li><img src="${page.resdomain}/resources/s1/image/201403/20140323085933_5579.jpg" alt="七天教育"/></li>
      <li><img src="${page.resdomain}/resources/s1/image/201403/20140323090012_7736.jpg" alt="七天教育培训中心"/></li>
      <li><img src="${page.resdomain}/resources/s1/image/201403/20140323090109_8270.jpg" alt="网络教育"/></li>
      <li><img src="${page.resdomain}/resources/s1/image/201403/20140323090132_5173.jpg" alt="职业园长"/></li>
  </ul><!--<div id="scroll-logger"></div>-->
  <div id="fla_pager" class="pager"></div>
</div>
</div></div>