//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JR.Stand.Toolkit.HttpTag {
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JR.DevFw.Toolkit.Tags.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 body
        ///{
        ///    font-size:12px;color:#666;
        ///}
        ///a{color:#0066cc;}
        ///a:hover{color:#006699;}
        ///h1{display:none;}
        ///table{background:#f0f0f0;width:100%;}
        ///th{border-bottom:solid 1px #e5e5e5;background:#006699;color:White;font-size:12px;line-height:23px;}
        ///td{background:white;font-size:12px;padding:2px;line-height:23px;}
        ///td.center{text-align:center;}
        ///input.button{border:outset 1px #f0f0f0;}
        ///td input{border:solid 1px #DCE5F1;padding:1px;line-height:16px;height:20px;width:100%;color:#006699}
        ///td input.ck{border:none [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string managestyle {
            get {
                return ResourceManager.GetString("managestyle", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 &lt;!DOCTYPE HTML PUBLIC &quot;-//W3C//DTD HTML 4.0 Transitional//EN&quot;&gt;
        ///&lt;html&gt;
        ///	&lt;head&gt;
        ///		&lt;title&gt;标签管理&lt;/title&gt;
        ///	    ${css}
        ///	&lt;/head&gt;
        ///	&lt;body&gt;
        ///    &lt;!--
        ///
        ///    //
        ///    // Copyright 2011 @ S1N1.COM,All rights reseved.
        ///    // Project : 奥博网站管理系统
        ///    // Name : 标签组件
        ///    // Author : Newmin (newmin.net@gmail.com)
        ///    // Create : 2011/08/28 16:27
        ///    // Product Link: http://www.ops.cc
        ///    //
        ///
        ///    --&gt;
        ///
        ///
        ///        &lt;h1&gt;标签管理&lt;/h1&gt;
        ///        &lt;form action=&quot;&quot; method=&quot;post&quot; target=&quot;tag_ifr&quot; enctype=&quot;application/x-www-form-u [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string tagsmanager {
            get {
                return ResourceManager.GetString("tagsmanager", resourceCulture);
            }
        }
    }
}
