<div class="page-top">
    <div class="page-center">
        <a href="${page.domain}/admin?source=front_site" target="_blank"><img src="${page.tpath}/theme/images/user.gif" alt="登陆"/></a>
        | &nbsp;<a href="/en/">英文</a> / <a href="/cn/">中文</a>
    </div>
</div>

<div class="page-header">
    <a href="${page.domain}/" class="logo"><h1>$site(name)</h1></a>
    <div class="page-search">
        <input type="text" class="page-search-input" value="请输入元器件型号......" onfocus="this.value='';"/><span class="page-search-button" onclick="location.replace('${page.domain}/search?w='+escape(this.previousSibling.value));">搜索</span>
    </div>
</div>

$navigator()


