//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.34003
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Ops.Cms.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Ops.Cms.Web.Resource.SiteResource", typeof(SiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to /* 所有样式表请引用此文件 */
        ///
        ////* 此文件由系统自动生成! */
        ///
        ////* @ ELEMENTS */
        ////*{vertical-align:middle;}*/
        ///img{border:none;}
        ///ul{list-style:none;}
        ///a{color:#0066cc;outline:none;}
        ///a:hover{color:#006699;}
        ////* @SELECTOR STYLE */
        ///.left{float:left;}
        ///.right{float:right;}
        ///.center{text-align:center;}
        ///.clear{clear:both;}
        ///.overflow{overflow:hidden;}
        ///.hidden{display:none;}
        ///.clearfix{clear:both;} /*用于清除浮动*/
        ///.pxh0{height:0px;}
        ///.hight_light,.search_hightlight,.special{color:Red;}
        ///.tleft{text-align:left;}
        ///
        ///
        ////* @元素样式表  (2012- [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string css_common {
            get {
                return ResourceManager.GetString("css_common", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////文件：UI基础库(ui,validate,form,table,scrollbar,form)
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;$V.14({30:{31:7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_cms_api {
            get {
                return ResourceManager.GetString("js_cms_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to // ***********************************************
        ///// Ops.Cms.NET Js Libaray  v4.5
        ///// 发布日期：2014-06-01 18:20
        ///// ***********************************************
        ///// 加载示例
        /////    global.js?hover=navi,clist,alist&amp;ld=：
        /////    对导航,栏目导航和文档导航设置样式为&quot;current&quot;
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { re [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_core {
            get {
                return ResourceManager.GetString("js_core", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////文件：数据表格插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;5 6(h,k){3.p=h.1j?h:$r.$(h);3.8=k.8;3.x=k.x||&quot;1k&quot;;3.F=k [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_datagrid {
            get {
                return ResourceManager.GetString("js_lib_datagrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////文件：对话框插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;6 r(e){3.k=M;3.9=1a;3.n=U 1I().1J()+1b(N.1K()*1c);3.p=e. [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_dialog {
            get {
                return ResourceManager.GetString("js_lib_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////文件：表单插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function(p,a,c,k,e,r){e=function(c){return(c&lt;a?&apos;&apos;:e(parseInt(c/a)))+((c=c%a)&gt;35?String.fromCharCode(c+29):c.toString(36))};if(!&apos;&apos;.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return&apos;\\w+&apos;};c=1};while(c--)if(k[c])p=p.replace(new RegExp(&apos;\\b&apos;+e(c)+&apos;\\b&apos;,&apos;g&apos;),k[c]);return p}(&apos;$A.B({C:{D:4(c){1 d=\&apos;\&apos;;1 f=3.p[c||0];1 g=4(a,b){q(1 i=0;i&lt;a.r;i++){b(a[i])}};1 h=E F();1 j=4(a){q(1 i=0;i&lt;h.r;i++){2(h[i]==a){9 G}}9 H};g [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_form {
            get {
                return ResourceManager.GetString("js_lib_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////文件：卷轴插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;$r.s({t:{u:2(a){3.7=a.7;3.n=a.n;3.o=a.o;3.7.4.v+=\&apos;w: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_roller {
            get {
                return ResourceManager.GetString("js_lib_roller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////文件：滚动条插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;3 H={$:Y Z(),6:k,5:k,10:{x:0,y:0},11:{x:0,y:0,z:-1},I: [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_scrollbar {
            get {
                return ResourceManager.GetString("js_lib_scrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////文件：滚动效果插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;8 9(b,c,d){3.$P=s;3.$C=s;3.$L=s;3.w=s;3.j=0;3.1c=0; [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_scroller {
            get {
                return ResourceManager.GetString("js_lib_scroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////名称 ： Table库
        /////版本:1.0
        /////时间：2012-09-22
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;$x.y({q:{z:7(f,g,h){4(f&amp;&amp;f.A===&quot;B&quot;){f.3+=\&apos; C-q\&apos;;l  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_table {
            get {
                return ResourceManager.GetString("js_lib_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////文件：UI基础库(ui,validate,form,table,scrollbar,form)
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;$V.14({30:{31:7 [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_ui {
            get {
                return ResourceManager.GetString("js_lib_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //
        /////文件：上传插件
        /////版本: 1.0
        /////时间：2013-10-01
        /////
        ///eval(function(p,a,c,k,e,r){e=function(c){return(c&lt;a?&apos;&apos;:e(parseInt(c/a)))+((c=c%a)&gt;35?String.fromCharCode(c+29):c.toString(36))};if(!&apos;&apos;.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return&apos;\\w+&apos;};c=1};while(c--)if(k[c])p=p.replace(new RegExp(&apos;\\b&apos;+e(c)+&apos;\\b&apos;,&apos;g&apos;),k[c]);return p}(&apos;4 h(a,b){2.6=a.6;2.y=a.K?7.A(a.K):B;2.L=14.15()*q+q;2.r=a.r||16;2.M=a.17,2.N=a.N,2.s=B;2.3=B;2.u;9 c=7.A(2.6);2.u=c.j||\&apos;选择文件\&apos;;c.j=\&apos;\&apos;;9  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_upload {
            get {
                return ResourceManager.GetString("js_lib_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to //===================== 验证器(2012-09-30) =====================//
        ///eval(function(p,a,c,k,e,r){e=function(c){return(c&lt;a?&apos;&apos;:e(parseInt(c/a)))+((c=c%a)&gt;35?String.fromCharCode(c+29):c.toString(36))};if(!&apos;&apos;.replace(/^/,String)){while(c--)r[e(c)]=k[c]||e(c);k=[function(e){return r[e]}];e=function(){return&apos;\\w+&apos;};c=1};while(c--)if(k[c])p=p.replace(new RegExp(&apos;\\b&apos;+e(c)+&apos;\\b&apos;,&apos;g&apos;),k[c]);return p}(&apos;$n.18({F:{y:6(e,a,b,c){3(b){4 d=e.5(\&apos;19\&apos;);3(d){d=$n.1a(d);3(d[b]){c=d[b]}}}3(e.5(\&apos;u\&apos;)){4 f=7.r(e.5(\&apos;u\&apos;));3(f){3(f.N [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_lib_validate {
            get {
                return ResourceManager.GetString("js_lib_validate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;u 3c(a,b,c){b=1C(b);r(2J(c)==&quot;4z&quot;){8 c=19 1Q(c.22(&quot;-&quot;)[0],c.22(&quot;-&quot;)[1],c.22(&quot;-&quot;)[2])}r(2J(c)==&quot;4A&quot;){8 c= [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string js_ui_min {
            get {
                return ResourceManager.GetString("js_ui_min", resourceCulture);
            }
        }
    }
}
