<div id="i_contact" style="font-size:105%">
		    <p class="title">$lang(contactus)</p>
            <div class="left_inner"><strong>Tel:</strong>&nbsp;$site(tel)<br />
<strong>Fax:</strong>&nbsp;$site(fax)<br />
<strong>E-mail:</strong>&nbsp;<a href="mailto:$site(email)">$site(email)</a><br />
<!--&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;-->
<a href="mailto:zhuyongdong@gmail.com">zhuyongdong@gmail.com</a><br />
    <strong>Subscribe us:</strong><br />
    <div>
     <a href="https://www.facebook.com/machinerylms" target="_blank">
        <img src="/resources/s1/image/201407/20140725133846_3135.gif" style="border:0;width:180px"/></a>&nbsp;
        
    <a href="https://www.youtube.com/user/machinerylms" target="_blank">
        <img src="/resources/s1/image/201407/20140725133914_4072.gif" style="border:0;width:180px"/></a><!--<br />
        <a href="http://lnzmachinery.en.alibaba.com/" target="_blank">
        <img src="/resources/s2/image/201405/20140520043132_3662.gif" style="border:0;width:20px"/>
        Alibaba</a>-->
    </div>
<strong>Add:</strong>&nbsp;$site(address)</div>

		</div>        
