<script type="text/javascript">
    /* var lft_btm =document.getElementById('left_btm');
    var footer = document.getElementById('footer');
    lft_btm.style.paddingTop=(footer.offsetTop-lft_btm.offsetTop-10)+'px';
  var _gaq = _gaq || [];
  _gaq.push(['_setAccount', 'UA-16053978-25']);
  _gaq.push(['_trackPageview']);

  (function() {
    var ga = document.createElement('script'); ga.type = 'text/javascript'; ga.async = true;
    ga.src = ('https:' == document.location.protocol ? 'https://ssl' : 'http://www') + '.google-analytics.com/ga.js';
    var s = document.getElementsByTagName('script')[0]; s.parentNode.insertBefore(ga, s);
  })();
*/

  (function(i,s,o,g,r,a,m){i['GoogleAnalyticsObject']=r;i[r]=i[r]||function(){
  (i[r].q=i[r].q||[]).push(arguments)},i[r].l=1*new Date();a=s.createElement(o),
  m=s.getElementsByTagName(o)[0];a.async=1;a.src=g;m.parentNode.insertBefore(a,m)
  })(window,document,'script','//www.google-analytics.com/analytics.js','ga');

  ga('create', 'UA-661455-2', 'auto');
  ga('send', 'pageview');

    
</script>


<div id="header">
<div id="languages"><a href="/cn/" rel="nofollow"><img alt="LMS中国" src="${page.tpath}/country/cn.gif" />chinese[中文]</a>
    <a href="/es/" rel="nofollow"><img alt="LMS西班牙" src="${page.tpath}/country/es.gif" />Espa&ntilde;ol</a>
<a href="/en/" rel="nofollow" ><img alt="LMS英语" src="${page.tpath}/country/en.gif" />English</a>
<a href="/thai/" rel="nofollow" ><img alt="LMS泰国" src="${page.tpath}/country/thai.gif" />ภาษาไทย</a>
    
    </div>
    
<div id="logo"><a title="roll forming machines" href="http://www.lmsmachinery.com"><img alt="LMS Roll Forming Machines" src="/images/logo.jpg" /></a></div>
<div id="keywords">
<p><b>INTERNATIONAL</b> LIMITED</p>
<p><span>MACHINERY MANUFACTURER</span></p>
</div>
<div id="search_form"><input id="SearchStr" type="text" />
    <button style="cursor: pointer" id="BtnSearch" onclick="Search_Click()">GO</button><img alt="" src="/images/big.gif" />
    </div>
<div id="mainnav">
<ul>
    <li><a title="Home" href="${page.domain}/"><span>$lang(home)</span></a></li>
        <li><a title="About Us" href="${page.domain}/service/aboutus.html"><span>$lang(aboutus)</span></a></li>
            <li><a title="Products" href="${page.domain}/product.html"><span>$lang(product)</span></a></li>
    <li><a title="News" href="${page.domain}/news/"><span>$lang(news)</span></a></li>
    <li><a title="Galleries" href="${page.domain}/gallery/"><span>$lang(galleries)</span></a></li>
    <li><a title="Video" href="${page.domain}/video/"><span>$lang(video)</span></a></li>
    <li><a title="Feedback" href="${page.domain}/service/feedback.html"><span>$lang(feedback)</span></a></li>
    <li><a title="Contact Us" href="${page.domain}/service/contactus.html"><span>$lang(contactus)</span></a></li>
</ul>
</div>
</div>

