<div class="F--Top"></div>
<div class="F--Cen">
  <div class="inner">
    <div class="F--Cen-l Fl DG2">
      <div class="CON--cen-pd2 clear">
        <span style="line-height: 2;">地址：$site(address)</span><br />
        <span style="line-height: 2;">电话：$site(tel)</span><br />
        手机：$site(phone)<br />
        <span style="line-height: 2;">网站：www.j6.cc</span><div class="clear"></div>
      </div>
    </div>
    <div class="F--Cen-r Fr DG2">

      <div class="foot-nav">
        <a href='#'  title='加盟条件'>加盟条件</a>
        <span>|</span>
        <a href='#'  title='在线加盟'>在线加盟</a>
        <span>|</span>
        <a href='#'  title='公司新闻'>公司新闻</a>
        <span>|</span>
        <a href='#'  title='人才招聘'>人才招聘</a>
        <span>|</span>
        <a href='#'  title='友情链接'>友情链接</a>
        <span>|</span>
        <a href='#'  title='企业历程'>企业历程</a>
        <span>|</span>
        <a href='#'  title='联系我们'>联系我们</a>
      </div>
      <div class="foot-text">
        <p>
          $site(name) 版权所有 沪ICP备888888号
        </p>
        <p>
          电话：$site(tel)  QQ:$site(qq)  Email:$site(email)
        </p>

      </div>
    </div>
  </div>
  <div class="clear"></div>
</div>