<style type="text/css">
    .bannerBG{background:#e3e3e3;}
#fla{margin:0 auto;}
#fla ul{list-style:none;margin:0;padding:0;}
#fla ul li{float:left;padding:0 1px;}
#fla_pager{position:absolute;bottom:-2px;}
    .flashDiv .pager{position:absolute;bottom:0;right:0px;margin:0;overflow:hidden;}
    .flashDiv .pager a{display:inline-block;border:solid 0px #666;/*padding:4px 8px;*/
        background:#fff;text-decoration:none;color:#fff;font-weight:bold;
       height:5px; width:240px;text-indent:-999em;
    	}
    .flashDiv .pager a.current{background:#006fab;color:#666;}
    .flashDiv img{width:960px;}
</style>
<div class="bannerBG">
<div style="width:960px;margin:0 auto;">
<div class="center flashDiv" id="fla" style="height:405px;overflow:hidden">
  <ul>
      <li><img src="${page.tpath}/theme/banner/01.jpg" alt="图片1"/></li>
      <li><img src="${page.tpath}/theme/banner/02.jpg" alt="图片2"/></li>
      <li><img src="${page.tpath}/theme/banner/03.jpg" alt="图片3"/></li>
      <li><img src="${page.tpath}/theme/banner/02.jpg" alt="图片4"/></li>
  </ul><!--<div id="scroll-logger"></div>-->
  <div id="fla_pager" class="pager"></div>
</div>
    <!--
<script type="text/javascript">
    cms.lazyRun(function(){
        cms.scroller('fla',{unit:200},5000);
    });
</script>-->
</div></div>