<!-- 页脚文件 -->
<div id="footer" style="position:relative">
    <div class="links">
        $link('3','<a href="{url}" target="{target}">{text}</a> |',0) <a href="#top">回到顶部</a>
    </div>
    Copyright 2012 © $site('name') 版权所有. 地址:$site('address')<br />
    <a href="/nanfeng/juanzeng.html" style="font-size:14px;color:red;font-weight:bold;text-decoration:none;font-family:'微软雅黑';">
        您的爱心将会帮助更多的老人,<span style="color:green">点击捐赠</span>
            或拨打捐赠热线:$site('tel')
    </a>
    
    <span class="donta" style="position:absolute;right:5px;top:20px">
        <img src="/uploads/image/201306/20130619230119_9207.gif" style="height:60px"/>
    </span>
    <br/><br/>
    
</div>