<div id="header">
    <div id="logo"><a href="/"></a></div>
    <div id="topnav">
        <b><a href="/xueli/" title="学历教育">学历教育</a></b>
	<a href="/xueli/zikao/">自学考试</a> . <a href="/xueli/chengkao/">成人高考</a> . <a href="/xueli/dianda/">
            电大开放教育</a> . <a href="/xueli/wangxiao/">网络教育</a> . <a href="/xueli/gaoshengzhuan/">高升专</a>
         . <a href="/xueli/zhuanshengben/">专升本</a>
	<a href="/xueli/">更多...</a>
 <br />
	<b><a href="/zgkz/" title="资格考试">资格考试</a></b>
         <a href="/zgkz/zgzs/">职业资格</a> . <a href="/caikuai/">财经类</a> . <a href="/zgkz/law/">法律类</a> . <a href="/zgkz/gongcheng/">
            工程类</a> . <a href="/zgkz/yiyao/">医药卫生类</a> .
        <a href="/zgkz/pclevel/">计算机</a> . <a href="/caikuai/">会计证</a>
	<a href="/zgkz/" title="更多...">更多...</a>
    <br />
	<b><a href="/kaoyan/" title="在职读研">在职读研</a></b>
    <a href="/kaoyan/shuoyi/">在职硕士</a> . <a href="/kaoyan/boshi/">在职博士</a> . <a href="/kaoyan/mba/">
            MBA</a> . <a href="/kaoyan/mba/">EMBA</a> . <a href="/kaoyan/liuxue/">国外留学</a>
        . <a href="/kaoyan/yanxiu/">研修班</a>
	<a href="/kaoyan/" title="更多...">更多...</a>
    </div>
    <div class="rlink">
        <ul>
          <li class="r1"><a href="#" onclick="this.style.behavior='url(#default#homepage)';this.setHomePage('http://www.0345.cc');" >设为首页</a></li>
          <li class="r2"><a href="javascript:void(0);" onClick="window.external.AddFavorite(document.location.href,document.title)">加入收藏</a></li>
          <li class="r3"><a href="/" >网站地图</a></li>
          <li class="r4"><a href="/admin" rel="nofollow" >管理登录</a></li>
        </ul>
    </div>
</div>

<div id="navigation">
    <ul>
        <li class="l"></li>
        <li style="background: none;"><a id="mm1" onmouseover="setn(this,1);" href="/">主页</a>
        </li>
        <li><a id="mm2" onmouseover="setn(this,2);" href="/about/aboutus.html">机构简介</a>
        </li>
        <li><a id="mm3" onmouseover="setn(this,3);" href="/xueli/">学历教育</a> </li>
        <li><a id="mm4" onmouseover="setn(this,4);" href="/zgkz/">资格考试</a> </li>
        <li><a id="A1" onmouseover="setn(this,5);" href="/lang/">语言培训</a> </li>
        <li><a id="mm5" onmouseover="setn(this,6);" href="/kaoyan/">在职读研</a> </li>
        <li><a id="mm6" onmouseover="setn(this,7);" href="/caikuai/">财会考试</a> </li>
        <li><a id="mm7" onmouseover="setn(this,8);" href="/gongcheng/">建筑工程</a></li>
        <li><a id="mm8" onmouseover="setn(this,9);" href="/zxx/" style="color:red">中小学教育平台</a></li>
        <li><a id="mm10" onmouseover="setn(this,10);" href="http://www.chsi.com.cn/xlcx/"
            target="_blank">成绩|证书查询</a></li>
        <li class="r"></li>
    </ul>
</div>
<div id="subnav">
    <p id="sn2">
        <a href="/about/aboutus.html">七天教育在线简介</a> | <a href="/about/jiagou.html">组织机构</a>
        | <a href="/about/shizililiang.html">师资力量</a> | <a href="/about/contactus.html">
            联系我们</a>
    </p>
    <p id="sn3" style="margin-left: 85px! important; margin-left: 35px">
        <a href="/zikao/">自学考试</a> | <a href="/chengkao/">成人高考</a> | <a href="/dianda/">
            电大开放教育</a> | <a href="/wangxiao/">网络教育</a> | <a href="/gaoshengzhuan/">高升专</a>
        | <a href="/zhuanshengben/">专升本</a>
    </p>
    <p id="sn4" style="display: none; margin-left: 50PX;">
        <a href="/guojiwuliu/">国际物流师</a> | <a href="/yingxiao/">营销师</a> | <a href="/baojian/">
            报检员</a> | <a href="/xlzx/">心理咨询师</a> | <a href="/gendan/">跟单员</a>
        | <a href="/danzheng/">单证员</a> | <a href="/dzisw/">电子商务师</a> | <a href="/scyx/">
            市场营销员</a> | <a href="/diangong/">电工上岗证</a> | <a href="/rlzy/">人力资源管理师</a>
        | <a href="/zgzs/">资格证书</a> | <a href="/zhichengkaoshi/">职称考试</a>
    </p>
    <p id="sn5" style="margin-left: 180px! important; margin-left: 90px">
        <a href="/jp/">日语</a> | <a href="/france/">法语</a> | <a href="/deyu/">
            德语</a> | <a href="/eyu/">俄语</a> | <a href="/en/">英语|公共英语|商务英语</a>
        | <a href="/otherlang/">其他语言</a> | <a href="/studyguid/">外语学习指南</a> |
        <a href="/langarchive/">外语学习资料</a>
    </p>
    <p id="sn6" style="margin-left: 180px! important; margin-left: 90px">
        <a href="/shuoyi/">在职硕士</a> | <a href="/boshi/">在职博士</a> | <a href="/mba/">
            MBA</a> | <a href="/emba/">EMBA</a> | <a href="/liuxue/">国外留学</a>
        | <a href="/yanxiu/">研修班</a>
    </p>
    <p id="sn7" style="margin-left: 330px! important; margin-left: 125px">
        <a href="/chukuai/">初级会计职称</a> | <a href="/caikuai_zhongkuai/">中级会计职称</a>
        | <a href="/caikuai_zhucekuaiji/">注册会计师</a> | <a href="/caikuai_zhuceshuiw/">注册税务师</a>
    </p>
    <p id="sn8" style="margin-left: 360px! important; margin-left: 190px">
        <a href="/gongcheng_tumu/">土木工程</a> | <a href="/gongcheng_paishui/">给水排水工程</a> |
        <a href="/gongcheng_gczaojiao/">工程造价</a>
    </p>
    <p id="sn9" style="margin-left: 457px! important; margin-left: 235px">
        <a href="/fengxian_xly/">训练营</a> | <a href="/fengxian_xyban/">研修班</a> | <a href="/fengxian_neixun/">
            企业内训</a> | <a href="/fengxian_cerm/">CERM培训</a> | <a href="/fengxian_pinggu/">风险评估专业人员职业资格证书</a>
    </p>
    <p id="sn10" style="margin-left: 677px! important; margin-left: 335px">
        <a href="#" target="_blank">在线成绩查询</a> | <a href="http://www.chsi.com.cn/xlcx/" target="_blank">
            在线证书查询</a>
    </p>
    <p id="sn11" style="margin-left: 685px! important; margin-left: 335px"></a>
    </p>
</div>
<div id="slogon">$site(notice)
</div>




<div id="souke">
    <a href="#" class="so"></a>
            <select id="selSchool">
                    <option value="">--选择城市--</option>
                
                    <option value="禅城"> 禅城 </option>
                
                    <option value="南海"> 南海 </option>
                
                    <option value="顺德"> 顺德 </option>
                
                    <option value="高明"> 高明 </option>
                
                    <option value="三水"> 三水 </option>
                
                    <option value="广州"> 广州 </option>
                
                    <option value="深圳"> 深圳 </option>
                
                    <option value="珠海"> 珠海 </option>
                
                    <option value="东莞"> 东莞 </option>
                
                    <option value="中山"> 中山 </option>
                
                    <option value="茂名"> 茂名 </option>
                
                    <option value="江门"> 江门 </option>
                
                    <option value="梅州"> 梅州 </option>
                
                    <option value="汕头"> 汕头 </option>
                
                    <option value="湛江"> 湛江 </option>
                
                    <option value="惠州"> 惠州 </option>
                
            </select>
    <input type="text" id="sokey" value="请输入你要查找的课程"/><a href="#" class="button" id="btnso"></a>
</div>

<script type="text/javascript" src="${page.fpath}/global.js?ld=scroller&hover=navi,clist&ver=${page.version}"></script>
<script type="text/javascript">
    cms.$('sokey').onfocus=function(){
        this.value='';
    };
    
    cms.$('sokey').onblur=function(){
        if(this.value=='')this.value='请输入你要查找的课程';
    };
    cms.$('btnso').onclick=function(){
        var key=this.previousSibling.value;
        if(key.length!=0)
            location.href='/search?c=3&w='+escape(cms.val('selSchool'))+escape(key)+'&area='+escape(cms.val('selSchool'));
        else alert('请输入你要查找的课程!');
    };
</script>

<div class="clear"></div>