
<div id="other">
		    <p class="title">$lang(welcome)</p>
            <ul>
                <li><a title="New product of roll forming machines" href="${page.domain}/product/">$lang(professional)$lang(space)$lang(choice)</a></li>
                <li><a title="Feedback of roll forming machines" href="${page.domain}/service/feedback.html">
                    $lang(professional)$lang(space)$lang(service)</a></li>
            </ul>

</div>
