<!-- 页脚文件 -->
<div id="footer">
    <div class="footer-main">
        <div class="footer-logo"></div>
        <div class="footer-follow"></div>
        <div class="footer-links">
            <a href="#">TOP</a> $link(3,'|<a href="{url}"{target}>{text}</a>',-1)
        </div>
        <div class="footer-main-contact">
            <ul>
                <li>${site.tel}1</li>
                <li>${site.address}</li>
                <li>${site.email}</li>
        	</ul>
        </div>
        
         Copyright(C)2010-2014 ${site.name}&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;
    </div>
</div>
    

