<div style="background:#036eb8;padding-top:20px;">
  
    <div style="background:#fff;width:940px;margin:0 auto;padding:30px 0 10px 10px;">
     
       	 <img src="${page.tpath}/theme/images/img_${category.tag}.gif" height="44" width="126" alt="${category.name}"/>
		
        <div class="category_title">
            ${category.name}<br />
            <em id="category_title_em">${category.tag}</em>
        </div>
        <script>
            var cem=document.getElementById('category_title_em');
        	cem.innerHTML=cem.innerHTML.toUpperCase();
        </script>
    </div>
</div>