<div class="mod-footer">
    <div class="container">
        <div class="mod-footer-col col-md-4 col-sm-4 hidden-xs">
            <h3 class="tit">$lang(contact)$lang(space)$lang(us)</h3>
            <ul>
                <li><i>电话:</i> $site(tel)</li>
                <li class="hidden-xs"><i>邮箱:</i> $site(email)</li>
                <li class="hidden-xs"><i>微信:</i> $site(im)</li>
            </ul>
            

        </div>
        <div class="mod-footer-col col-md-2 col-xs-6 hidden-sm">
            <h3 class="tit">客户服务</h3>
            <ul>
                <li><a href="">联系我们</a></li>
                <li><a href="">服务流程</a></li>
                <li><a href="">付款方式</a></li>
                <li><a href="">疑问解答</a></li>
            </ul>
        </div>
        <div class="mod-footer-col col-md-2 col-xs-6 hidden-sm">
            <h3 class="tit">信息资讯</h3>
            <ul>
                <li><a href="">关于我们</a></li>
                <li><a href="">隐私策略</a></li>
                <li><a href="">新闻动态</a></li>
            </ul>
        </div>
        <div class="mod-footer-col mod-footer-copy col-md-4 col-sm-8 col-xs-12">
            <div class="mod-footer-owner">
                @ DevSofts 2009 - 2019
                
            </div>
            <div class="mod-footer-contact">
                佛山市益信软件开发有限公司
            </div>
            <div class="mod-footer-power">
                网站使用<a target="_blank" href="//to2.net/cms">${page.version}</a>创建
                <span class="mod-footer-beian">
                    <a href="http://www.miitbeian.gov.cn/" target="_blank">粤ICP备15066003号</a>
                </span>
            </div>
        </div>
    </div>
</div>
<script type="text/javascript">
var _stat_callback = function(data){
      var stat_str = JSON.stringify(data);
    var raw_cookie = $b.cookie.read("_stat_data");
    if(data["from"] != "-" || raw_cookie === ""){
        $b.cookie.write("_stat_data",stat_str,100000000000);
    }else{
        stat_str =  raw_cookie|| stat_str;
    }
    console.log(stat_str);
    //$b.$fn(".stat-from-field").val(stat_str);
};
(function(c) {
   var s = document.createElement("SCRIPT");
   s.src = "http://s.to2.net/static/domain_stat.js?a8d97566&callback="+c;
   var f = document.getElementsByTagName("SCRIPT")[0];
   f.parentNode.insertBefore(s, f);
})("_stat_callback");
</script>