

<header class="mod-header scroll-link clearfix">
    <div class="row">
        <div class="col-md-2 col-sm-2 col-xs-3">
            <div class="mod-header-logo">
                <img src="${page.tpath}/css/images/logo.png" width="120"/>
                <a class="mask" href="/"></a>
            </div>
        </div>

        <div class="col-md-8 col-sm-7 col-xs-12">
            $navigator()
        </div>
        
        <div class="col-md-2 col-sm-3 mod-header-sub hidden-xs gra-txt-right">
            <a class="gra-circle-button gra-circle-button-small" href="/about/experts.html" onclick="popFeedback();return false;">在线联系技术专家</a>
        </div>
        <div class="hidden-md hidden-sm mod-header-nav-toggle gra-text-right">
            <i class="fa fa-bars"></i>
        </div>
    </div>

    <div class="clearfix"></div>
</header>

<script type="text/javascript">
    $b.$fn(".mod-header-nav-toggle").click(function(){
        var nav = $b.$fn(".mod-navigator");
        var expand = this.hasClass("expanded");
        if(expand){
            this.removeClass("expanded");
            nav.slideUp("fast",function(){
                nav.css({"display":"none"});
            });
        }else{
            this.addClass("expanded");
            nav.css({"display":"inherit"});
            nav.slideDown("fast");
        }
        this.find("i").attr("class",expand?"fa fa-bars":"fa fa-close");

    });
</script>