//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.42000
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace JR.Cms.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JR.Cms.Web.Resource.SiteResource", typeof(SiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 @charset &quot;UTF-8&quot;;
        ///
        ////*!
        /// * animate.css -http://daneden.me/animate
        /// * Version - 3.7.0
        /// * Licensed under the MIT license - http://opensource.org/licenses/MIT
        /// *
        /// * Copyright (c) 2018 Daniel Eden
        /// */
        ///
        ///@-webkit-keyframes bounce{0%,20%,53%,80%,to{-webkit-animation-timing-function:cubic-bezier(.215,.61,.355,1);-webkit-transform:translateZ(0);animation-timing-function:cubic-bezier(.215,.61,.355,1);transform:translateZ(0)}40%,43%{-webkit-animation-timing-function:cubic-bezier(.755,.05,.855,.06);-webkit-transform:tra [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string animate {
            get {
                return ResourceManager.GetString("animate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 
        ///function JR(){this.VERSION=&apos;3.2&apos;;this.WORKPATH=&apos;&apos;;this._Extend_PROTOTYPE=true;this._eventArray=[&quot;abort&quot;,&quot;blur&quot;,&quot;change&quot;,&quot;click&quot;,&quot;dblclick&quot;,&quot;error&quot;,&quot;focus&quot;,&quot;keydown&quot;,&quot;keypress&quot;,&quot;keyup&quot;,&quot;load&quot;,&quot;mousedown&quot;,&quot;mousemove&quot;,&quot;mouseout&quot;,&quot;mouseover&quot;,&quot;mouseup&quot;,&quot;reset&quot;,&quot;resize&quot;,&quot;select&quot;,&quot;submit&quot;,&quot;unload&quot;];this.__init__=function(){var a=document.getElementsByTagName(&apos;SCRIPT&apos;);var s=a[a.length-1];var b=s.src;this.WORKPATH=b.replace(/(\/)[^/]+$/,&apos;$1&apos;);if(this._Extend_PROTOTYPE){this.__extendingJsPrototype__()}this.dom.set [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string base_min {
            get {
                return ResourceManager.GetString("base_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 // ***********************************************
        ///// jr.Cms.NET Js Libaray  v4.5
        ///// 发布日期：2014-06-01 18:20
        ///// ***********************************************
        ///// 加载示例
        /////    global.js?hover=navi,clist,alist&amp;ld=：
        /////    对导航,栏目导航和文档导航设置样式为&quot;current&quot;
        /////
        ///function JR() { this.__VERSION__ = &apos;3.1&apos;; this.__WORKPATH__ = &apos;&apos;; this.__Extend_PROTOTYPE__ = true } JR.prototype = { __init__: function () { if (this.__Extend_PROTOTYPE__) { this.__extendingJsPrototype__() } var f = document.getElementsByTagName(&apos;SCRIPT&apos;); var s = [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cms_core_min {
            get {
                return ResourceManager.GetString("cms_core_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：Cms Javascript WebApi
        /////版本: 0.0.1
        /////时间：2014-06-21
        ///// Note : 请调用API前，先调用jr.spi.setPath(&apos;${page.domain}&apos;);这样才能请求到指定站点的接口。
        ///// Modify :  2015-09-18 19:37  [jsix] [!] : 重构
        /////
        ///if (!window.j6) alert(&apos;未加载core.js！&apos;);
        ///jr.extend({
        ///    api: {
        ///        path: &apos;&apos;,
        ///        setPath:function(p) {
        ///            this.path = p;
        ///        },
        ///        request: function (apiName, params, call, errCall) {
        ///            var uri = this.path + &apos;/webapi?key=11857832134&amp;name=&apos; + apiName;
        ///            for (var key in params) {
        ///            [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_cms_api {
            get {
                return ResourceManager.GetString("js_cms_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：动画插件
        /////版本: 1.0
        /////时间：2014-11-06
        /////
        ///jr.extend({ animation: { timer: function (a, b, c, d, e) { if (!a) return; var f = c != null ? c : 0; var g = d != null ? d : 100; var h = 0; var i = 0; if (e &lt; 1 || e &gt; 5) { h = (d - c) &lt; 0 ? -e : e; i = 20 } else { h = (g - f) / (4 * (6 - e)); h *= (Math.abs(g - f) / 100); i = 1000 / h; i = i &lt; 0 ? -Math.ceil(i) : Math.floor(i); if (i &lt; 30) i = 30 } var t = setInterval(function () { f = f + h; if (Math.abs(f) &gt;= Math.abs(g)) { f = g; if (b instanceof Function) b() [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_animation {
            get {
                return ResourceManager.GetString("js_lib_animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：数据表格插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///function datagrid(h, k) { this.panel = h.nodeName ? h : jr.$(h); this.columns = k.columns; this.idField = k.idField || &quot;id&quot;; this.data_url = k.url; this.data = k.data; this.onLoaded = k.loaded; this.loadbox = null; this.gridView = null; this.loading = function () { if (this.gridView.offsetHeight == 0) { var a = this.gridView.previousSibling.offsetHeight; var b = this.panel.offsetHeight - this.gridView.previousSibling.offsetHeight; this.gridView.style.cssText = thi [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_datagrid {
            get {
                return ResourceManager.GetString("js_lib_datagrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：对话框插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///function simpleDialog(e) { this._simgpleDialog = true; this.window = window; this.win = window; this.doc = null; this.id = new Date().getMilliseconds() + parseInt(Math.random() * 100); this.title = e.title; this.usedrag = e.drag; this.style = e.style || &apos;ui-dialog&apos;; this.setupFade = !e.setupFade ? e.setupFade : true; this.onclose = e.onclose; this.canNotClose = e.canClose == false; if (e.cross != false) { while (this.win.parent != this.win) { this.win = this.win.pa [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_dialog {
            get {
                return ResourceManager.GetString("js_lib_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*
        ///* file：表单及验证插件
        ///* version : 1.0
        ///* date：2011-10-01
        ///* history :
        ///*  2014-12-07 18:57 [!] : 修改验证器
        ///*/
        ///jr.extend({ form: { getData: function (a) { var b = &apos;&apos;; var c = document.forms[a || 0]; return jr.json.toQueryString(c) }, asyncSubmit: function (a, b) { var c = document.forms[a || 0]; var d = document.getElementById(&apos;$async_ifr&apos;); if (!d) { try { d = document.createElement(&apos;&lt;iframe name=&quot;$async_ifr&quot;&gt;&apos;) } catch (ex) { d = document.createElement(&apos;iframe&apos;); d.setAttribute(&apos;name&apos;, &apos;$async_ifr&apos;) } d.setAttribute( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_form {
            get {
                return ResourceManager.GetString("js_lib_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：卷轴插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///
        ///jr.extend({ roller: { init: function (a) { this.elem = a.elem; this.direction = a.direction; this.pix = a.pix; this.elem.style.cssText += &apos;overflow:hidden;&apos; }, start: function (a, b) { var c = this.elem, _pix = this.pix, a = a | 1; var i, j; var d; var e = function () { if (b != null) b() }; switch (this.direction) { case &quot;up&quot;: i = _pix; j = 0; d = setInterval(function () { i -= a; if (i &lt; 0) { i = 0; clearInterval(d); e() } c.style.height = i.toString() + &quot;px&quot; },  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_roller {
            get {
                return ResourceManager.GetString("js_lib_roller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：滚动条插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///var JS_scrollbar = { $: window.j6, pnode: null, ele: null, startP: { x: 0, y: 0 }, moveP: { x: 0, y: 0, z: -1 }, slideBar: null, init: function (e) { this.ele = e.nodeName ? e : document.getElementById(e); this.pnode = document.createElement(&apos;DIV&apos;); this.slideBar = null; this.timer = null; var a = this.ele.parentNode; a.insertBefore(this.pnode, this.ele); this.pnode.appendChild(this.ele); this.pnode.className = &apos;scrollbar&apos;; this.pnode.style.cssText += &apos;height:&apos; + t [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_scrollbar {
            get {
                return ResourceManager.GetString("js_lib_scrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：滚动效果插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///
        ///function scroller(b, c, d) { this.$P = null; this.$C = null; this.$L = null; this.pagePanel = null; this.index = 0; this.offset = 0; this.scroll = 0; this.scrollUnit = c.unit || 5; this.lock = false; this.direction = c.direction || &apos;left&apos;; this.interval = d; this.timer = null; this.taskTimer = null; this.$P = document.getElementById(b); this.$P.style.cssText += &apos;overflow:hidden;position:relative;&apos;; var f = this.$P.getElementsByTagName(&apos;UL&apos;); if (f.length == 0) {  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_scroller {
            get {
                return ResourceManager.GetString("js_lib_scroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////名称 ： Table库
        /////版本:1.0
        /////时间：2012-09-22
        /////
        ///jr.extend({ table: { dynamic: function (f, g, h) { if (f &amp;&amp; f.nodeName === &quot;TABLE&quot;) { f.className += &apos; ui-table&apos;; var j = f.getElementsByTagName(&apos;TH&apos;); window.jr.each(j, function (i, e) { if (i != j.length - 1) { if ((e.getElementsByClassName ? e.getElementsByClassName(&apos;th-split&apos;) : document.getElementsByClassName(&apos;th-split&apos;, e)).length == 0) { var a = document.createElement(&quot;SPAN&quot;); a.className = &apos;th-split&apos;; e.appendChild(a) } } }); var k = f.getElementsByTagNam [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_table {
            get {
                return ResourceManager.GetString("js_lib_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：UI基础库(ui,validate,form,table,scrollbar,form)
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///
        ///function HS_DateAdd(a, b, c) { b = parseInt(b); if (typeof (c) == &quot;string&quot;) { var c = new Date(c.split(&quot;-&quot;)[0], c.split(&quot;-&quot;)[1], c.split(&quot;-&quot;)[2]) } if (typeof (c) == &quot;object&quot;) { var c = c } switch (a) { case &quot;y&quot;: return new Date(c.getFullYear() + b, c.getMonth(), c.getDate()); break; case &quot;m&quot;: return new Date(c.getFullYear(), c.getMonth() + b, checkDate(c.getFullYear(), c.getMonth() + b, c.getDate())); break; case &quot;d&quot;: return [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_ui {
            get {
                return ResourceManager.GetString("js_lib_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：上传插件
        /////版本: 1.0
        /////时间：2013-10-01
        /////
        ///function fileUpload(h, i) { this.id = h.id; this.infopanel = h.info ? document.getElementById(h.info) : null; this.processID = Math.random() * 100 + 100; this.debug = h.debug || false; this.uploadurl = h.url, this.processurl = h.processurl, this.filename = null; this.file = null; this.repeatSelect = h.repeatSelect == undefined ? false : h.repeatSelect; this.btnText = &apos;&apos;; this.btnClicked = false; this.repeatSelect = false; var j = document.getElementById(this.id); th [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_upload {
            get {
                return ResourceManager.GetString("js_lib_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 *{box-sizing:border-box}
        ///
        ///
        ////* ---------- 页面元素定义样式 --------- */
        ///a,abbr,acronym,address,applet,big,blockquote,body,caption,
        ///cite,code,dd,del,dfn,div,dl,dt,em,font,form,h1,h2,h3,h4,h5,
        ///h6,html,i,iframe,img,ins,kbd,label,legend, li,object,ol,p,
        ///pre,q,s,samp,small,span,strike,strong,table, tbody,td,tfoot,
        ///th,thead,tr,tt,ul,var{  margin:0;padding:0;border:0;outline:0;
        ///    font-weight:inherit;font-style:normal;font-family:inherit;
        ///    text-decoration:none;-webkit-text-size-adjust:none;
        ///    -ms-interpola [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string site_base {
            get {
                return ResourceManager.GetString("site_base", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 body{color:#333;font-family:Arial &apos;MiCROSOFT YAHEI&apos;;/*background:#F0F0F0;*/}
        ///
        ///h1,h2,h3{margin:0;padding:0;}
        ///h1{font-size:1.25em;line-height: 2em;}
        ///a:link,a:visited{color:#333;}
        ///a:hover{color:#D50000;}
        ///.relative{position: relative;}
        ///.pull{float:left;}
        ///.push{margin-right:3%;float:left;}
        ///.arrow{background:url(img/arrow.gif) no-repeat;width:10px;height:10px;display:inline-block;margin-right:3px;}
        ///.panel{width:1019px;margin:0 auto;font-size:1.2em;}
        ///table{border:solid 1px #333;}
        ///table td{border:solid 1px #333;pad [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string site_page {
            get {
                return ResourceManager.GetString("site_page", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*! WOW wow.js - v1.2.1 - 2016-09-05
        ///* https://wowjs.uk
        ///* Copyright (c) 2016 Thomas Grainger; Licensed MIT */!function (a, b) { if (&quot;function&quot; == typeof define &amp;&amp; define.amd) define([&quot;module&quot;, &quot;exports&quot;], b); else if (&quot;undefined&quot; != typeof exports) b(module, exports); else { var c = { exports: {} }; b(c, c.exports), a.WOW = c.exports } }(this, function (a, b) { &quot;use strict&quot;; function c(a, b) { if (!(a instanceof b)) throw new TypeError(&quot;Cannot call a class as a function&quot;) } function d(a, b) { return b.ind [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string wow {
            get {
                return ResourceManager.GetString("wow", resourceCulture);
            }
        }
    }
}
