
    <div class="gra-big-tit">我们的优势</div>
    <div class="col-md-3 col-sm-3 col-xs-6">
        <div class="it">
            <img src="${page.tpath}/css/images/our-adv-icon@2x.png" title="软件定制开发"/>
            <h3>服务省心</h3>
            <i>我们有多年软件定制和行业经验您只需告之您的想法就可开始</i>
        </div>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-6">
        <div class="it">
            <img src="${page.tpath}/css/images/our-adv-icon-1@2x.png" title="软件定制开发"/>
            <h3>经验丰富</h3>
            <i>软件研发均来自上海、拥有数十年的软件研发经验</i>
        </div>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-6">
        <div class="it">
            <img src="${page.tpath}/css/images/our-adv-icon-2@2x.png" title="软件定制开发"/>
            <h3>灵活可变</h3>
            <i>我们拥有超强的需求分析和业务架构能力，可灵活应对您需求的变更</i>
        </div>
    </div>
    <div class="col-md-3 col-sm-3 col-xs-6">
        <div class="it">
            <img src="${page.tpath}/css/images/our-adv-icon-3@2x.png" title="软件定制开发"/>
            <h3>终身使用</h3>
            <i>一次性开发费用、终身使用源码、数据交付客户不额外收费</i>
        </div>
    </div>