using System;
using System.IO;
using System.Text;
using JR.Cms.Conf;
using JR.Stand.Core;
using JR.Stand.Core.Framework;
using JR.Stand.Core.Utils;

namespace JR.Cms.Web.Resource
{
    /// <summary>
    /// 站点静态资源初始化
    /// </summary>
    public class SiteResourceInit
    {
        private static Logger logger = Logger.Factory(typeof(SiteResourceInit));
        const string Comment = "/* Warning! the file is auto generated by system. */\r\n";
        const string CssComment = " /* The file is auto generated by system. */\r\n";

        /// <summary>
        /// 初始化
        /// </summary>
        public static void Init()
        {
            ExtraMasterAssets();
            // robots.txt
            ExtraFile("robots.txt", GetResource("Web/Resource/SiteResources/site-robots.txt"));
            // robots.txt
            InitFavicon();
            // 释放base.min.css
            Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "base.min.css",
                CssComment + ResourceUtility.CompressHtml(
                               GetResource("Web/Resource/SiteResources/site-base.css"))
                               + "\n /* merge elements.css */\n"
                               + ResourceUtility.CompressHtml(
                                   GetResource("Web/Resource/SiteResources/site-elements.css"))
                               + "\n /* merge pages.css */\n"
                               + ResourceUtility.CompressHtml(
                                   GetResource("Web/Resource/SiteResources/site-pages.css"))
                               + "\n /* merge migration.css */\n"
                               + ResourceUtility.CompressHtml(
                                   GetResource("Web/Resource/SiteResources/site-migration.css"))
                               + "\n /* merge animate.css */\n"
                                + ResourceUtility.CompressHtml(
                                   GetResource("Web/Resource/SiteResources/Assets/animate.css"))
                                   , false);

            //Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "cms.js", 
            //    comment + SiteResource.cms_core_min, !true);

            Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "base.min.js",
                Comment + GetResource("Web/Resource/SiteResources/base.min.js")
                + "\n /* merge js_lib_scroller.js */\n"
                + ResourceUtility.CompressHtml(GetResource("Web/Resource/SiteResources/Assets/js_lib_scroller.js"))
                + "\n /* merge cms.core.js */\n"
                    + ResourceUtility.CompressHtml(GetResource("Web/Resource/SiteResources/cms.core.js")), false);

            Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "api.js",
                Comment + GetResource("Web/Resource/SiteResources/js-cms-api.js"), false);

            //
            // Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/ui.js",
            //     comment + GetResource("js_lib_ui.js"), false);
            //
            //
            // Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/dialog.js",
            //     comment + GetResource("js_lib_dialog.js"), false);
            //
            // Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/form.js",
            //     comment + GetResource("js_lib_form.js"), false);
            //
            // Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/datagrid.js",
            //     comment + GetResource("js_lib_datagrid.js"), false);
            //
            Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/scroller.js",
                Comment + GetResource("Web/Resource/SiteResources/Assets/js_lib_scroller.js"), false);

            // Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/scrollbar.js",
            //     comment +GetResource("js_lib_scrollbar.js"), false);
            //
            // Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/roller.js",
            //     comment + GetResource("js_lib_roller.js"), false);
            //
            // Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/table.js",
            //     comment + GetResource("js_lib_table.js"), false);
            //
            // //Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/validate.js",
            // //    comment + SiteResource.js_lib_validate, false);
            //
            // Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/upload.js",
            //     comment + GetResource("js_lib_upload.js"), false);
            //
            // Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/animation.js",
            //     comment + GetResource("js_lib_animation.js"), false);

            // animate.css
            Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "animate.css", Comment +
                                                                      GetResource("Web/Resource/SiteResources/Assets/animate.css"), false);
            // wow.js
            Reset(CmsVariables.FRAMEWORK_ASSETS_PATH + "js/wow.js", Comment + GetResource("Web/Resource/SiteResources/Assets/wow.js"), false);
        }

        private static void InitFavicon()
        {
            try
            {
                //todo: 释放后文件提示无法打开, 故采用复制的方式
                //ExtraFile("favicon.ico", GetResource("Web/Resource/SiteResources/site-favicon.ico"));
                string dstPath = EnvUtil.GetBaseDirectory() + "favicon.ico";
                string fromPath = CmsVariables.FRAMEWORK_PATH + "assets/site-favicon.ico";
                if (!File.Exists(dstPath))
                {
                    File.Copy(fromPath, dstPath);
                }
            }
            catch (Exception ex)
            {
                logger.Error("释放favicon错误:" + ex.Message);
            }
        }

        private static void ExtraMasterAssets()
        {
            Reset(CmsVariables.FRAMEWORK_PATH + "mui/js/base.js",
                Comment + GetResource("Web/Resource/ManageResources/manage_js.js"), false);
            Reset(CmsVariables.FRAMEWORK_PATH + "mui/js/component.js",
                Comment + GetResource("Web/Resource/ManageResources/ui_component.source.js"), false);
        }

        private static string GetResource(string fileName)
        {
            return ResourcesReader.Read(typeof(SiteResourceInit).Assembly, fileName);
        }

        /// <summary>
        /// 释放文件,如果文件存在则忽略
        /// </summary>
        /// <param name="filePath">文件路径</param>
        /// <param name="content">内容</param>
        private static void ExtraFile(string filePath, string content)
        {
            var fileName = $"{EnvUtil.GetBaseDirectory()}/{filePath}";
            var file = new FileInfo(fileName);

            try
            {
                if (file.Exists)
                {
                    return;
                }

                Console.WriteLine("---" + fileName);
                var data = Encoding.UTF8.GetBytes(content);

                using (var fs = new FileStream(fileName, FileMode.OpenOrCreate, FileAccess.Write))
                {
                    fs.SetLength(0);
                    fs.Write(data, 0, data.Length);
                    fs.Flush();
                    fs.Dispose();
                }
            }
            catch (Exception ex)
            {
                logger.Error("释放资源失败,文件:" + fileName + "; 错误信息:" + ex.StackTrace);
            }
        }
        private static void Reset(string filePath, string content, bool keepBak)
        {
            var fileName = $"{EnvUtil.GetBaseDirectory()}/{filePath}";
            var file = new FileInfo(fileName);

            try
            {
                if (keepBak && file.Exists)
                {
                    var bakFile = new FileInfo(fileName + ".bak");
                    if (bakFile.Exists) bakFile.Delete();
                    File.Move(fileName, fileName + ".bak");
                }

                var data = Encoding.UTF8.GetBytes(content);

                using (var fs = new FileStream(fileName, FileMode.OpenOrCreate, FileAccess.Write))
                {
                    fs.SetLength(0);
                    fs.Write(data, 0, data.Length);
                    fs.Flush();
                    fs.Dispose();
                }
            }
            catch
            {
            }
        }


        private delegate void ExtractTemplate(string templateName, byte[] data);

        /// <summary>
        /// 释放默认的模板包
        /// </summary>
        [Obsolete]
        private static void ExtractDefaultTemplatePack()
        {
            /*
            string tplRootPath= String.Format("{0}templates/", EnvUtil.GetBaseDirectory());
            MemoryStream ms ;
            IArchiveModel archive;
            DirectoryInfo dir;

            ExtractTemplate et = (tpl, zipData) =>
            {
                dir = new DirectoryInfo(tplRootPath + tpl);

                //模板不存在,则解压
                if (!dir.Exists)
                {
                    ms = new MemoryStream(zipData);

                    archive = ArchiveFactory.Open(ms);

                    foreach (IArchiveModelEntry entry in archive.Entries)
                    {
                        if (!entry.IsDirectory)
                        {
                            entry.WriteToDirectory(tplRootPath, ExtractOptions.ExtractFullPath | ExtractOptions.Overwrite);
                        }
                    }

                    archive.Dispose();
                    ms.Dispose();
                }
            };

            //Default Template
            et("default", SiteResource.tpl_default);

            //Diy Templates
            et("diy", SiteResource.tpl_diy);
            */
        }
    }
}