//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     运行时版本:4.0.30319.34209
//
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。
// </auto-generated>
//------------------------------------------------------------------------------

namespace J6.Cms.Web.Resource {
    using System;
    
    
    /// <summary>
    ///   一个强类型的资源类，用于查找本地化的字符串等。
    /// </summary>
    // 此类是由 StronglyTypedResourceBuilder
    // 类通过类似于 ResGen 或 Visual Studio 的工具自动生成的。
    // 若要添加或移除成员，请编辑 .ResX 文件，然后重新运行 ResGen
    // (以 /str 作为命令选项)，或重新生成 VS 项目。
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class SiteResource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal SiteResource() {
        }
        
        /// <summary>
        ///   返回此类使用的缓存的 ResourceManager 实例。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("J6.Cms.Web.Resource.SiteResource", typeof(SiteResource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   使用此强类型资源类，为所有资源查找
        ///   重写当前线程的 CurrentUICulture 属性。
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   查找类似 // ***********************************************
        ///// J6.Cms.NET Js Libaray  v4.5
        ///// 发布日期：2014-06-01 18:20
        ///// ***********************************************
        ///// 加载示例
        /////    global.js?hover=navi,clist,alist&amp;ld=：
        /////    对导航,栏目导航和文档导航设置样式为&quot;current&quot;
        /////
        ///function j6l() { this.__VERSION__ = &apos;3.1&apos;; this.__WORKPATH__ = &apos;&apos;; this.__Extend_PROTOTYPE__ = true } j6l.prototype = { __init__: function () { if (this.__Extend_PROTOTYPE__) { this.__extendingJsPrototype__() } var f = document.getElementsByTagName(&apos;SCRIPT&apos;) [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string cms_core_min {
            get {
                return ResourceManager.GetString("cms_core_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：Cms Javascript WebApi
        /////版本: 0.0.1
        /////时间：2014-06-21
        /////
        ///if (!window.j6) alert(&apos;未加载core.js！&apos;);
        ///j6.extend({
        ///    api: {
        ///        path:&apos;&apos;,
        ///        request: function (apiName, params, call, errCall) {
        ///            var uri = this.path+&apos;/webapi?key=11857832134&amp;name=&apos; + apiName;
        ///            for (var key in params) {
        ///                uri += &apos;&amp;&apos; + key + &apos;=&apos; + params[key];
        ///            }
        ///            j6.xhr.request({ uri: uri, params: {}, method: &apos;GET&apos;, data: &apos;json&apos; }, {
        ///                success: call,
        /// [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_cms_api {
            get {
                return ResourceManager.GetString("js_cms_api", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：动画插件
        /////版本: 1.0
        /////时间：2014-11-06
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;$o.S({T:{q:9(a,b,c,d,e){8(!a)r;7 f=c!=x?c:0;7 g=d!=x?d:n; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_animation {
            get {
                return ResourceManager.GetString("js_lib_animation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：数据表格插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;5 6(h,k){3.p=h.1j?h:$r.$(h);3.8=k.8;3.x=k.x||&quot;1k&quot;;3.F=k [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_datagrid {
            get {
                return ResourceManager.GetString("js_lib_datagrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：对话框插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;5 s(e){3.1O=P;3.t=t;3.9=t;3.k=K;3.l=Q 1P().1Q()+1e(R.1R( [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_dialog {
            get {
                return ResourceManager.GetString("js_lib_dialog", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 /*
        ///* file：表单及验证插件
        ///* version : 1.0
        ///* date：2011-10-01
        ///* history :
        ///*  2014-12-07 18:57 [!] : 修改验证器
        ///*/
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_form {
            get {
                return ResourceManager.GetString("js_lib_form", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：卷轴插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;$r.s({t:{u:2(a){3.7=a.7;3.n=a.n;3.o=a.o;3.7.4.v+=\&apos;w: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_roller {
            get {
                return ResourceManager.GetString("js_lib_roller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：滚动条插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;3 u={$:j.$n,6:m,5:m,Z:{x:0,y:0},10:{x:0,y:0,z:-1},M:m,v: [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_scrollbar {
            get {
                return ResourceManager.GetString("js_lib_scrollbar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：滚动效果插件
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;8 9(b,c,d){3.$P=s;3.$C=s;3.$L=s;3.w=s;3.j=0;3.1c=0; [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_scroller {
            get {
                return ResourceManager.GetString("js_lib_scroller", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////名称 ： Table库
        /////版本:1.0
        /////时间：2012-09-22
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;$x.y({q:{z:7(f,g,h){4(f&amp;&amp;f.A===&quot;B&quot;){f.3+=\&apos; C-q\&apos;;l  [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_table {
            get {
                return ResourceManager.GetString("js_lib_table", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：UI基础库(ui,validate,form,table,scrollbar,form)
        /////版本: 1.0
        /////时间：2011-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] } ]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p } (&apos;$V.14({30:{31:7 [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_ui {
            get {
                return ResourceManager.GetString("js_lib_ui", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 //
        /////文件：上传插件
        /////版本: 1.0
        /////时间：2013-10-01
        /////
        ///eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;3 q(h,i){2.8=h.8;2.N=h.Z?9.O(h.Z):P;2.10=1n.1o()*F+F;2.G= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_lib_upload {
            get {
                return ResourceManager.GetString("js_lib_upload", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 eval(function (p, a, c, k, e, r) { e = function (c) { return (c &lt; a ? &apos;&apos; : e(parseInt(c / a))) + ((c = c % a) &gt; 35 ? String.fromCharCode(c + 29) : c.toString(36)) }; if (!&apos;&apos;.replace(/^/, String)) { while (c--) r[e(c)] = k[c] || e(c); k = [function (e) { return r[e] }]; e = function () { return &apos;\\w+&apos; }; c = 1 }; while (c--) if (k[c]) p = p.replace(new RegExp(&apos;\\b&apos; + e(c) + &apos;\\b&apos;, &apos;g&apos;), k[c]); return p }(&apos;u 3c(a,b,c){b=1C(b);r(2J(c)==&quot;4z&quot;){8 c=19 1Q(c.22(&quot;-&quot;)[0],c.22(&quot;-&quot;)[1],c.22(&quot;-&quot;)[2])}r(2J(c)==&quot;4A&quot;){8 c= [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string js_ui_min {
            get {
                return ResourceManager.GetString("js_ui_min", resourceCulture);
            }
        }
        
        /// <summary>
        ///   查找类似 body{font:62.5% Sans-Serif,Arial;margin:0;}
        ///img{border:none;}
        ///a{outline:none;}
        ///a:link,a:visited{color:#0000FF;}
        ///mask,.mask{background:url(/framework/assets/images/mask.gif);
        ///	width:100%;opacity:0.2;alpha(opacity=20);position:absolute;top:0;left:0;}
        ///
        ///
        ////* +++++++++++++ Classes ++++++++++++++ */
        ///
        ///.left{float:left;}
        ///.right{float:right;}
        ///.center{text-align:center;}
        ///.clear,.clear-fixcler{clear:both;}
        ///.overflow{overflow:hidden;}
        ///.hidden{display:none;}
        ///.clearfix{clear:both;}
        ///.nom{margin:auto;}
        ///div [字符串的其余部分被截断]&quot;; 的本地化字符串。
        /// </summary>
        internal static string template {
            get {
                return ResourceManager.GetString("template", resourceCulture);
            }
        }
    }
}
