<div class="clear"></div>
<p id="footer">
<a href="/about/aboutus.html">关于七天</a> | <a href="/about/rongyu.html">发展概况</a> | <a href="/about/shizililiang.html">师资力量</a> | <a href="/college/">合作院校</a> | 
<a href="/about/job.html">人才招聘</a> | <a href="#">培训合作</a> | <a href="#/sitemap.html">网站地图</a> | <a href="/about/contactus.html">联系我们</a>
    <br>Copyright (C) 2006 - 2013 ${site.name}版权所有<br />
    联系电话：${site.tel}  公司地址：${site.address}<br>
网址：www.0345.cc   E-mail：service@0345.cc  技术支持:<a href="http://www.j6.cc" style="font-weight:normal;">奥博软件</a>  粤ICP备09189988号
<br />本站由"<strong><a href="http://www.j6.cc/cms/" style="color:#006699">奥博建站系统</a></strong>"驱动
<script src="http://49722.fy.kf.qycn.com/vclient/state.php?webid=49722" language="javascript" type="text/javascript"></script>
<span style="display:none"><!--
<script language="javascript" src="http://count9.51yes.com/click.aspx?id=97100689&logo=1" charset="gb2312"></script>-->
<script src="http://s6.cnzz.com/stat.php?id=5260176&web_id=5260176&online=2" language="JavaScript"></script>
</span>
</p>
</div>