<style type="text/css">
    .bannerBG{}
#fla{margin:1px auto;}
#fla ul{list-style:none;margin:0;padding:0;}
#fla ul li{float:left;padding:0 1px;position:relative;}
    .flashDiv .flash-pager{position:absolute;bottom:0;left:484px;margin:0;overflow:hidden;text-align:center;}
    .flashDiv .flash-pager a{display:inline-block;margin-left:4px;
        background:#fff;text-decoration:none;color:#fff;font-weight:bold;
        height:16px; width:16px;text-indent:-0em;overflow:hidden;line-height:16px;
        background:url(${page.tpath}/themes/focus_point.gif) -16px center no-repeat;
    	}
    .flashDiv .flash-pager a.current{color:#fff;background-position:0 center;}
    .flashDiv img{width:1000px;}

  .flashDiv div.scroll{position:absolute;top:20px;left:30px;}
</style>
<div class="bannerBG">
<div style="width:1000px;margin:0 auto;">
<div class="center flashDiv" id="fla" style="height:450px;overflow:hidden;">
  <ul>
      <li><a href="javascript:;"><img src="${page.tpath}/themes/banner/002.jpg" alt="${site.name}" /></a></li>
      <li><a href="javascript:;">
      <img src="${page.tpath}/themes/banner/001.jpg" alt="${site.name}"/></a>
      <!--
      <div class="scroll">
        <h2><a href="/guide/caizhuangpeixun.html">为什么要学习彩妆?</a></h2>
        <p>彩妆师 - 被评为21世纪的女性最佳职业之一！</p>
      </div>-->
      </li><!--
      <li><a href="javascript:;"><img src="${page.tpath}/theme/banner/03.jpg" alt="${site.name}"/></a></li>
      <li><a href="javascript:;"><img src="${page.tpath}/theme/banner/02.jpg" alt="${site.name}"/></a></li>-->
  </ul><!--<div id="scroll-logger"></div>-->
  <div id="fla_pager" class="flash-pager"></div>
</div>
    <!--
<script type="text/javascript">
    cms.lazyRun(function(){
        cms.scroller('fla',{unit:200},5000);
    });
</script>-->
</div></div>